scheme("SiftScreenshots")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)

devices([
  "iPhone 16 Pro",
  "iPhone 16 Pro Max",
  "iPad Pro 13-inch (M4)"
])

languages(["en-US"])
