scheme("SiftScreenshots")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)

devices([
  "iPhone 17 Pro",
  "iPhone 17 Pro Max",
  "iPad Pro 13-inch (M5)"
])

languages(["en-US"])
